server:
  port: 8088
  servlet:
    context-path: /secondhouse/

spring:
  application:
    name: secondhouse
  datasource:
    url: jdbc:mysql://localhost:3306/secondhouse?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
#      - classpath:sql/table.sql
#    initialization-mode: always
#    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
